### ISSUE TITLE
How can I find gsn file based on different model?

### ISSUE THREAD

**Issue by OmarAshkar** [SysBioChalmers/Kiwi#3]
Hello, 

I'd like to incoprate in package in my analysis. But the pathway names are different from what I need. I am using Mouse-GEM metabolic model. 

Is there is a script to generate gsn file?

Thank You,
Omar

**Comment by varemo** [comment]
Hi, yes you probably need to parse out the GSN from your model. There exists scripts, depending on the model format you use. Perhaps @edkerk could share if you have anything available? Unfortunately I've been out of the GEM loop for many years...

**Comment by OmarAshkar** [comment]
Thank you for your response. Actually, the problem is bigger than that and it seems that this tool has many dependency incompatibilities that the example itself is not running. I will try to fix it when I have time. 

Thank you very much!
